// Schema.voices.Add("Class", "Text", "Real Text.", "sound")

local function AddVoice(text, realtext, sound)
    Schema.voices.Add("Biotic", text, realtext, sound)
end

AddVoice("ACCEPT CHARGE", "Accept the charge.", "vortigaunt/ep2/acceptcharge.wav")
AddVoice("ACCEPT ENERGY", "Accept energy.", "vortigaunt/ep2/acceptenergy.wav")
AddVoice("GLADLY ACCOMPANY", "Gladly we accompany.", "vortigaunt/ep2/accompany.wav")
AddVoice("ALERT", "Alert!", "vortigaunt/ep2/alert.wav")
AddVoice("ALL FOR NOW", "That is all for now.", "vortigaunt/ep2/allfornow.wav")
AddVoice("ALL IN ONE", "All in one and one in all!", "vortigaunt/ep2/allinoneinall.wav")
AddVoice("ALLOW RECHARGE", "Allow us to recharge your cells.", "vortigaunt/ep2/allowrecharge.wav")
AddVoice("ALL WE CAN SPARE", "That is all we can spare.", "vortigaunt/ep2/allwecanspare.wav")
AddVoice("ALL WE HAVE", "All we have is yours.", "vortigaunt/ep2/allwehave.wav")
AddVoice("ASSENT", "Assent.", "vortigaunt/ep2/assent.wav")
AddVoice("THIS BODY", "This body is yours to command.", "vortigaunt/ep2/bodyyours.wav")
AddVoice("CAUTION", "Caution!", "vortigaunt/ep2/caution.wav")
AddVoice("WE DEDICATE", "We dedicate ourselves to your purpose!", "vortigaunt/ep2/dedicate.wav")
AddVoice("DONE", "Done!", "vortigaunt/ep2/done.wav")
AddVoice("DREAMED", "We have dreamed of this moment!", "vortigaunt/ep2/dreamed.wav")
AddVoice("EMPOWER US", "Empower us!", "vortigaunt/ep2/empowerus.wav")
AddVoice("ENERGY EMPOWERS US", "It's energy empowers us!", "vortigaunt/ep2/energyempower.wav")
AddVoice("FOR FREEDOM", "For freedom!", "vortigaunt/ep2/forfreedom.wav")
AddVoice("FORWARD", "Forward.", "vortigaunt/ep2/forward.wav")
AddVoice("GIVE OVER", "Give over your essence!", "vortigaunt/ep2/giveover.wav")
AddVoice("GLADLY", "Gladly.", "vortigaunt/ep2/gladly.wav")
AddVoice("GLORIOUS END", "To our glorious end!", "vortigaunt/ep2/gloriousend.wav")
AddVoice("HALT", "Halt!", "vortigaunt/ep2/halt.wav")
AddVoice("HERE", "Here.", "vortigaunt/ep2/here.wav")
AddVoice("HERE WE STAY", "Here we stay.", "vortigaunt/ep2/herewestay.wav")
AddVoice("HOLD", "Hold.", "vortigaunt/ep2/hold.wav")
AddVoice("HOLD STILL CANNOT CHARGE", "Hold still, or we cannot charge you!", "vortigaunt/ep2/holdorcantcharge.wav")
AddVoice("HOLD STILL", "Hold still.", "vortigaunt/ep2/holdstill.wav")
AddVoice("HONOR WE FOLLOW", "To our honor, we follow you.", "vortigaunt/ep2/honorfollow.wav")
AddVoice("HONOR IS OURS", "The honor is ours.", "vortigaunt/ep2/honorours.wav")
AddVoice("IF YOU MOVE", "If you move, we cannot help you.", "vortigaunt/ep2/ifyoumove.wav")
AddVoice("LEAD ON", "Lead on.", "vortigaunt/ep2/leadon.wav")
AddVoice("LEAD US", "Lead us.", "vortigaunt/ep2/leadus.wav")
AddVoice("MOVING TARGET", "We cannot heal a moving target.", "vortigaunt/ep2/movingtarget.wav")
AddVoice("MUTUAL", "Our purpose is mutual.", "vortigaunt/ep2/mutual.wav")
AddVoice("NODE NEXUS", "Node Nexus, feed upon this life!", "vortigaunt/ep2/nodenexus.wav")
AddVoice("ONWARD", "Onward!", "vortigaunt/ep2/onward.wav")
AddVoice("OUR PLACE", "Our place is here.", "vortigaunt/ep2/ourplacehere.wav")
AddVoice("PASS ON", "Pass on!", "vortigaunt/ep2/passon.wav")
AddVoice("WITH PLEASURE", "With pleasure.", "vortigaunt/ep2/pleasure.wav")
AddVoice("PREPARE TO RECEIVE", "Prepare to receive energy.", "vortigaunt/ep2/prepare.wav")
AddVoice("PREVAIL", "We shall prevail!", "vortigaunt/ep2/prevail.wav")
AddVoice("PROPITIOUS", "Propitious alliance.", "vortigaunt/ep2/propitious.wav")
AddVoice("REGRETTABLE", "This is regrettable.", "vortigaunt/ep2/regrettable.wav")
AddVoice("RETURN TO AlL", "Return to the all in one!", "vortigaunt/ep2/returntoall.wav")
AddVoice("RETURN TO VOID", "Return to the void!", "vortigaunt/ep2/returnvoid.wav")
AddVoice("SATISFACTION", "Satisfaction!", "vortigaunt/ep2/satisfaction.wav")
AddVoice("STAND CLEAR", "Stand clear!", "vortigaunt/ep2/standclear.wav")
AddVoice("SURGE", "We surge!", "vortigaunt/ep2/surge.wav")
AddVoice("TETHER CUT", "The tether is cut!", "vortigaunt/ep2/tethercut.wav")
AddVoice("THAT IS ALL", "That is all.", "vortigaunt/ep2/thatisall.wav")
AddVoice("TO THE VOID", "To the void with you!", "vortigaunt/ep2/tothevoid.wav")
AddVoice("TROUBLE US NO MORE", "That one shall trouble us no more.", "vortigaunt/ep2/troubleus.wav")
AddVoice("UNDESERVING", "Undeserving of consciousness!", "vortigaunt/ep2/undeserving.wav")
AddVoice("EXCELLENT", "Excellent!", "vortigaunt/ep2/vort_excellent.wav")
AddVoice("EXCELLENT SHOOTING", "Excellent shooting!", "vortigaunt/ep2/vort_excellentshooting.wav")
AddVoice("EXCELLENT SHOT", "Excellent shot!", "vortigaunt/ep2/vort_excellentshot.wav")
AddVoice("EXCEPTIONAL", "Exceptional.", "vortigaunt/ep2/vort_exceptional.wav")
AddVoice("GOOD TO FIGHT", "It is good that you now fight with us.", "vortigaunt/ep2/vort_goodfightwithus.wav")
AddVoice("GOOD TOGETHER", "It is good now that we work together.", "vortigaunt/ep2/vort_goodtogether.wav")
AddVoice("JUST SO", "Just so.", "vortigaunt/ep2/vort_grp_agree01.wav")
AddVoice("AGREED", "Agreed.", "vortigaunt/ep2/vort_grp_agree02.wav")
AddVoice("HMMM", "Hmmm.", "vortigaunt/ep2/vort_grp_agree03.wav")
AddVoice("AH", "Ah...", "vortigaunt/ep2/vort_grp_agree04.wav")
AddVoice("YES2", "Yes...", "vortigaunt/ep2/vort_grp_agree05.wav")
AddVoice("INDEED", "Indeed...", "vortigaunt/ep2/vort_grp_agree06.wav")
AddVoice("WELL STATED", "Well stated.", "vortigaunt/ep2/vort_grp_agree07.wav")
AddVoice("SKILLS FORMIDABLE", "Your skills are formidable!", "vortigaunt/ep2/vort_skillsformidable.wav")
AddVoice("WARE", "Ware!", "vortigaunt/ep2/ware.wav")
AddVoice("WE ARE YOURS", "We are yours!", "vortigaunt/ep2/weareyours.wav")
AddVoice("WE CLAIM YOU", "We claim you!", "vortigaunt/ep2/weclaimyou.wav")
AddVoice("WE SHARE", "We will share the vortessance.", "vortigaunt/ep2/weshare.wav")
AddVoice("WE WILL CHARGE", "We will charge you.", "vortigaunt/ep2/wewillcharge.wav")
AddVoice("WE WILL HELP", "We will help you.", "vortigaunt/ep2/wewillhelp.wav")
AddVoice("YES!", "Yes!", "vortigaunt/ep2/yes.wav")
AddVoice("YES FORWARD", "Yes, forward.", "vortigaunt/ep2/yesforward.wav")
AddVoice("I WILL TAKE HER", "I will take her to my kin by another path.", "vo/outland_01/intro/vort_rbed_byanotherpath.wav")
AddVoice("SHELTERED LOCATION", "My kin will meet us at a sheltered location beneath the surface.", "vo/outland_01/intro/vort_rbed_companions01.wav")
AddVoice("MUST MOVE HER", "We must move her there quickly.", "vo/outland_01/intro/vort_rbed_companions02.wav")
AddVoice("YOU ARE UNHARMED", "I am pleased to see at least you are unharmed.", "vo/outland_01/intro/vort_rbed_freeman02.wav")
AddVoice("HEALING HER WILL REQUIRE", "Healing her will require more than what I alone can conjure.", "vo/outland_01/intro/vort_rbed_freeman04.wav")
AddVoice("SUMMON MY KIN", "Let me summon my kin.", "vo/outland_01/intro/vort_rbed_freeman05.wav")
AddVoice("HELP IN THE MINES", "Help awaits us in the mines.", "vo/outland_01/intro/vort_rbed_intomines02.wav")
AddVoice("HANDS OCCUPIED", "Our hands are occupied.", "vo/outland_01/intro/vort_rbed_letsgo01b.wav")
AddVoice("DESTROY ALL OBSTACLES", "Destroy all obstacles!", "vo/outland_01/intro/vort_rbed_letsgo01c.wav")
AddVoice("WE MUST HASTEN", "We must hasten.", "vo/outland_01/intro/vort_rbed_letsgo04a.wav")
AddVoice("HER STATE IS DELICATE", "Her state is delicate.", "vo/outland_01/intro/vort_rbed_letsgo04b.wav")
AddVoice("V9", "Chung... corrrrl... malae.", "vo/outland_01/intro/vort_rbed_vemotings01.wav")
AddVoice("WHAT HARM HAS COME", "What harm has come...", "vo/outland_01/intro/vort_rbed_whatharm.wav")
AddVoice("THERE ARE MANY ROUTES BELOW", "There are many routes to the dungeon below! I trust you can find your way to join us there.", "vo/outland_01/intro/vort_separation_goodbye02.wav")
AddVoice("IF NOT SACRIFICE NOT BE FORGOTTEN", "If not, your sacrifice shall not be forgotten!", "vo/outland_01/intro/vort_separation_goodbye03.wav")
AddVoice("YOU MUST DRAW THEIR AGGRESSION", "You must draw their aggression so I can hurry her to shelter.", "vo/outland_01/intro/vort_separation_leave03.wav")
AddVoice("SUCCESS", "Success!", "vo/outland_01/intro/vort_separation_success02.wav")
AddVoice("ALMOST VORTAL", "Almost vortal, this bound between you...", "vo/outland_02/junction/vort_junc_almostvortal.wav")
AddVoice("KIN SOME DISTANCE", "My kin are still some distance away.", "vo/outland_02/junction/vort_junc_assistance02.wav")
AddVoice("MUST NOT BE DISTURBED", "For now we must not be disturbed.", "vo/outland_02/junction/vort_junc_assistance03.wav")
AddVoice("COMBINE HUNTERS", "The Combine hunters cause dramatic injury.", "vo/outland_02/junction/vort_junc_badlyinjured02.wav")
AddVoice("BEHOLD", "Behold!", "vo/outland_02/junction/vort_junc_behold.wav")
AddVoice("FAREWELL", "Farewell!", "vo/outland_02/junction/vort_junc_bye01.wav")
AddVoice("GO SAFELY", "Go safely!", "vo/outland_02/junction/vort_junc_bye02.wav")
AddVoice("TRAVEL WELL", "Travel well!", "vo/outland_02/junction/vort_junc_bye03.wav")
AddVoice("EXHAUSTED THEIR NUMBER", "We have exhausted their immediate number.", "vo/outland_02/junction/vort_junc_exhausted.wav")
AddVoice("REQUIRE YOUR SIGNATURE", "We require your vortal signature!", "vo/outland_02/junction/vort_junc_fmsignature04.wav")
AddVoice("IMMEASURABLE LOSS", "We have a very immeasurable loss.", "vo/outland_02/junction/vort_junc_immeasurable.wav")
AddVoice("KILLED MANY ANTLIONS", "We killed many antlions.", "vo/outland_02/junction/vort_junc_killedmanyyet01.wav")
AddVoice("YET MORE REMAIN", "Yet many more remain.", "vo/outland_02/junction/vort_junc_killedmanyyet02.wav")
AddVoice("WE KNIT SHATTERED BONE", "We knit shattered bone, and restored circulatory integrity.", "vo/outland_02/junction/vort_junc_knit.wav")
AddVoice("LIE STILL", "Lie still...", "vo/outland_02/junction/vort_junc_liestill.wav")
AddVoice("MATTER OF HOURS", "A matter of hours.", "vo/outland_02/junction/vort_junc_matterhours.wav")
AddVoice("A MOMENT LONGER", "A moment longer.", "vo/outland_02/junction/vort_junc_momentlonger.wav")
AddVoice("NEXT MATTER", "Now to the next matter of urgency!", "vo/outland_02/junction/vort_junc_nextmatter.wav")
AddVoice("NO PULSE", "No pulse!", "vo/outland_02/junction/vort_junc_nopulse01.wav")
AddVoice("HER HEART HAS STOPPED", "Her heart has stopped!", "vo/outland_02/junction/vort_junc_nopulse02.wav")
AddVoice("THERE IS A QUICKENING", "Yes... there is a quickening!", "vo/outland_02/junction/vort_junc_quicken.wav")
AddVoice("QUIET THEM", "We shall quiet them.", "vo/outland_02/junction/vort_junc_quietthem.wav")
AddVoice("RIGHT ROAD", "No fear... we will put you on the right road.", "vo/outland_02/junction/vort_junc_rightroad.wav")
AddVoice("TRY TO RIsE", "Now, try carefully to rise.", "vo/outland_02/junction/vort_junc_rise.wav")
AddVoice("REGAINED INTEGRITY", "Her vortal form has regained integrity.", "vo/outland_02/junction/vort_junc_stabilizing02.wav")
AddVoice("SHE STIRS", "She stirs.", "vo/outland_02/junction/vort_junc_stirs.wav")
AddVoice("OUR DELAY", "Our delay... regrettable.", "vo/outland_02/junction/vort_junc_weweredelayed.wav")
AddVoice("DEFEND US", "Defend us!", "vo/outland_02/junction/vort_turret_defendus.wav")
AddVoice("WE NEED HELP", "We need help!", "vo/outland_02/junction/vort_turret_helpcall01.wav")
AddVoice("WE ARE UNDER ATTACK", "We are under attack!", "vo/outland_02/junction/vort_turret_helpcall04.wav")
AddVoice("PROTECT US", "Protect us!", "vo/outland_02/junction/vort_turret_protectus.wav")
AddVoice("I DESCEND", "I descend.", "vo/outland_03_04/tunnels/vort_04_elevator_descend_01.wav")
AddVoice("ANTLIONS", "Antlions!", "vo/outland_03_04/tunnels/vort_antlions_arrive_01.wav")
AddVoice("SAD FATE OF OTHERS", "The sad fate of these others... is our good fortune.", "vo/outland_03_04/tunnels/vort_breakweb02.wav")
AddVoice("GRIM PINATA", "Grim pinata.", "vo/outland_03_04/tunnels/vort_breakweb03.wav")
AddVoice("AGREED2", "Agreed.", "vo/outland_03_04/tunnels/vort_extract_agreed.wav")
AddVoice("AH YES", "Ah, yes!", "vo/outland_03_04/tunnels/vort_extract_ahyes.wav")
AddVoice("BARE SOME TRAITS", "You bare some traits we thought inate to vortikind.", "vo/outland_03_04/tunnels/vort_extract_bond02.wav")
AddVoice("ANTLION HUSBANDRY", "Antlion husbandry was once our ancestral practice.", "vo/outland_03_04/tunnels/vort_extract_bond03.wav")
AddVoice("EXTRACT MOST PRIZED", "The creatures exude many valuable compounds. But the extract is the most prized by far.", "vo/outland_03_04/tunnels/vort_extract_bond04.wav")
AddVoice("LARVAL EXTRACT", "Ah, excellent. A bounty of larval extract!", "vo/outland_03_04/tunnels/vort_extract_bounty01.wav")
AddVoice("TAKE A MOMENT", "This should only take a moment.", "vo/outland_03_04/tunnels/vort_extract_bounty02.wav")
AddVoice("CONSTANT OBSTACLES", "What next in the parade of constant obstacles?", "vo/outland_03_04/tunnels/vort_extract_constantobst.wav")
AddVoice("OUR DREAMS DO NOT FOLLOW", "I only hope our dreams do not follow them.", "vo/outland_03_04/tunnels/vort_extract_dreamsdonotfollow02.wav")
AddVoice("SECRETIONS", "Secretions of the finest quality!", "vo/outland_03_04/tunnels/vort_extract_finequality01.wav")
AddVoice("RIPE PERFECTION", "The scent of ripe perfection beckons.", "vo/outland_03_04/tunnels/vort_extract_hardwork01.wav")
AddVoice("A HUMAN IS NEEDED", "A human is needed!", "vo/outland_03_04/tunnels/vort_extract_humanmark.wav")
AddVoice("IMBIDE THE EXTRACT", "Join, now, as we imbide the extract!", "vo/outland_03_04/tunnels/vort_extract_imbibe.wav")
AddVoice("DEEP SUBMERSION", "This will necessitate deep submersion in the vortessance.", "vo/outland_03_04/tunnels/vort_extract_injuriesdeep02.wav")
AddVoice("JOIN ME", "Join me.", "vo/outland_03_04/tunnels/vort_extract_joinmefm02.wav")
AddVoice("EXPECT GREATER RESISTANCE", "Expect ever greater resistance as we proceed!", "vo/outland_03_04/tunnels/vort_extract_keen02.wav")
AddVoice("GREAT ANTICIPATION", "I will observe with great anticipation.", "vo/outland_03_04/tunnels/vort_extract_puzzling02.wav")
AddVoice("NO FINER COMPANION", "There is no finer companion.", "vo/outland_03_04/tunnels/vort_extract_yescompanion02.wav")
AddVoice("QUITE PLEASANT UNDER FOOT", "They are quite pleasant under foot, are they not?", "vo/outland_03_04/tunnels/vort_squishgrub01.wav")
AddVoice("PLEASING SOUND", "Ah... such a pleasing sound and sensation!", "vo/outland_03_04/tunnels/vort_squishgrub02.wav")
AddVoice("NO SENTRIES", "I do not see their sentries.", "vo/outland_05/canyon/vort_canyon_enclavesentries02.wav")
AddVoice("FAR FETCHED", "Such a theory is hardly far-fetched...", "vo/outland_05/canyon/vort_canyon_farfetch.wav")
AddVoice("SCATTERED COMBINE FORCES", "They gather and unite the scattered Combine forces...", "vo/outland_05/canyon/vort_canyon_podparade02.wav")
AddVoice("THEY MOVE NORTH", "They move north with great purpose!", "vo/outland_05/canyon/vort_canyon_purpose.wav")
AddVoice("SENTRIES SHOULD HAVE SPOTTED", "Puzzling. The sentries should have spotted us by now.", "vo/outland_05/canyon/vort_canyon_puzzling.wav")
AddVoice("OUR URGENT NEED", "They will understand our urgent need.", "vo/outland_05/canyon/vort_canyon_reside02.wav")
AddVoice("KILL IT WITHOUT CONSEQUENCE", "At this time you may kill it without consequence.", "vo/outland_05/canyon/vort_guard_killit.wav")
AddVoice("GUN POWERLESS", "The gun would appear to be powerless.", "vo/outland_06/bridge/vort_bridge_depleted02.wav")
AddVoice("IT HAS BEEN AN HONOR", "Likewise! And farewell... it has been an honor!", "vo/outland_06/bridge/vort_bridge_farewell.wav")
AddVoice("BONDS ARE OF NATURE", "Our bonds are of nature, and require no gratitude.", "vo/outland_06/bridge/vort_bridge_honored.wav")
AddVoice("MORE URGENT ERRAND", "I fear more urgent errand demands our attention.", "vo/outland_06/bridge/vort_bridge_hunt01.wav")
AddVoice("REGRETTABLY TRUE", "Regrettably true.", "vo/outland_11a/silo/vort_silo_regrettablytrue.wav")
AddVoice("COME", "Come!", "HLAComVoice/vortigaunt/come.wav")
AddVoice("COME ENTER", "Come! Enter.", "HLAComVoice/vortigaunt/comeenter.wav")
AddVoice("COME IN", "Come in, come in!", "HLAComVoice/vortigaunt/comeincomein.wav")
AddVoice("COOKING", "Cooking.", "HLAComVoice/vortigaunt/cooking.wav")
AddVoice("FOR GUIDANCE", "For guidance!", "HLAComVoice/vortigaunt/forguidance.wav")
AddVoice("GO", "Go!", "HLAComVoice/vortigaunt/go.wav")
AddVoice("BRAIN INJURY", "I have a brain injury.", "HLAComVoice/vortigaunt/ihaveabraininjury.wav")
AddVoice("WHY I BROUGHT YOU", "I must show you why I have brought you here.", "HLAComVoice/vortigaunt/imustshowyouwhy.wav")
AddVoice("IN HERE", "In here!", "HLAComVoice/vortigaunt/inhere.wav")
AddVoice("IT IS IMPORTANT", "It is important!", "HLAComVoice/vortigaunt/itisimportant.wav")
AddVoice("CLEAR THE PATH", "I will clear the path.", "HLAComVoice/vortigaunt/iwillclearthepath.wav")
AddVoice("LOOK HERE", "Look here!", "HLAComVoice/vortigaunt/lookhere.wav")
AddVoice("BRAIN INJURED", "My brain is injured!", "HLAComVoice/vortigaunt/mybrainisinjured.wav")
AddVoice("HE WILL BE", "Or... he will be...", "HLAComVoice/vortigaunt/orhewillbe.wav")
AddVoice("OW", "Ow.", "HLAComVoice/vortigaunt/ow.wav")
AddVoice("PLEASE COME", "Please! Come...", "HLAComVoice/vortigaunt/pleasecome.wav")
AddVoice("SUSTENANCE", "Sustenance!", "HLAComVoice/vortigaunt/sustenance.wav")
AddVoice("COMBINE HAVE OTHER", "The Combine have other of my kin.", "HLAComVoice/vortigaunt/thecombinehaveother.wav")
AddVoice("THEEE", "The...", "HLAComVoice/vortigaunt/theee.wav")
AddVoice("THEN YOU WILL", "Then you will.", "HLAComVoice/vortigaunt/thenyouwill.wav")
AddVoice("THERE", "There!", "HLAComVoice/vortigaunt/there.wav")
AddVoice("THERE2", "There!", "HLAComVoice/vortigaunt/there2.wav")
AddVoice("THERE3", "There!", "HLAComVoice/vortigaunt/there3.wav")
AddVoice("THERE4", "There!", "HLAComVoice/vortigaunt/there4.wav")
AddVoice("THIS WAY", "This way.", "HLAComVoice/vortigaunt/thisway.wav")
AddVoice("RIPPED FROM OURSELVES", "We are ripped from ourselves...", "HLAComVoice/vortigaunt/wearerippedfromourselves.wav")
AddVoice("TRAPPED IN THE DARK", "We have been trapped... in the dark.", "HLAComVoice/vortigaunt/wehavebeentrapped.wav")
AddVoice("WHAT THEY DO TO US ALL", "What they do to us all.", "HLAComVoice/vortigaunt/whattheydotousall.wav")
AddVoice("YESSS2", "Yes...", "HLAComVoice/vortigaunt/yesss.wav")
AddVoice("YOU ARE WELCOME", "You are welcome!", "HLAComVoice/vortigaunt/youarewelcome.wav")
AddVoice("SAVED MY KIN", "You have saved my kin!", "HLAComVoice/vortigaunt/youhavesavedmykin.wav")
AddVoice("YOU MUST GO", "You must go!", "HLAComVoice/vortigaunt/youmustgo.wav")
AddVoice("YOU RECEIVED MY MESSAGES", "You received my messages!", "HLAComVoice/vortigaunt/youreceived.wav")
AddVoice("YOU WILL BE WELCOME", "You will be welcome!", "HLAComVoice/vortigaunt/youwillbewelcome.wav")
AddVoice("COURAGE", "Courage!", "HLAComVoice/vortigaunt/courage.wav")
AddVoice("DO NOT GO", "Do not go yet!", "HLAComVoice/vortigaunt/donotgoyet.wav")
AddVoice("ENTER", "Enter...", "HLAComVoice/vortigaunt/enter.wav")
AddVoice("HE IS DEAD", "He is dead.", "HLAComVoice/vortigaunt/heisdead.wav")
AddVoice("I AM ALONE", "I am alone in my head...", "HLAComVoice/vortigaunt/iamalone.wav")
AddVoice("I AM DIMINISHED", "I am... diminished.", "HLAComVoice/vortigaunt/iamdiminished.wav")
AddVoice("I AM SEVERED", "I am severed from the vortessance...", "HLAComVoice/vortigaunt/iamsevered.wav")
AddVoice("I HAVE COME TO HELP", "I have come to help!", "HLAComVoice/vortigaunt/ihavecometohelp.wav")
AddVoice("I MUST SHOW YOU SOMETHING", "I must show you something...", "HLAComVoice/vortigaunt/imustshowyou.wav")
AddVoice("MATTER OF PERSPECTIVE", "It is a matter of perspective.", "HLAComVoice/vortigaunt/itisamatterofperspective.wav")
AddVoice("IVE BEEN WAITING", "I've been waiting for you.", "HLAComVoice/vortigaunt/ivebeenwaitingforyou.wav")
AddVoice("NO RIDDLES", "No riddles!", "HLAComVoice/vortigaunt/noriddles.wav")
AddVoice("NOW GO", "Now go.", "HLAComVoice/vortigaunt/nowgo.wav")
AddVoice("OUR PATHS DIVERGE", "Our paths diverge.", "HLAComVoice/vortigaunt/ourpathsdiverge.wav")
AddVoice("THE COMBINE", "The Combine, yes!", "HLAComVoice/vortigaunt/thecombineyes.wav")
AddVoice("THERE IS NO DISTANCE", "There is no distance between us.", "HLAComVoice/vortigaunt/thereisnodistancebetweenus.wav")
AddVoice("DISTANT FROM ME", "The vortessance is distant from me...", "HLAComVoice/vortigaunt/thevortessanceisdistant.wav")
AddVoice("THROUGH THERE", "Through there!", "HLAComVoice/vortigaunt/throughthere.wav")
AddVoice("WE ARE COTERMINOUS", "We are... coterminous.", "HLAComVoice/vortigaunt/wearecoterminus.wav")
AddVoice("WE CANNOT FAIL", "We cannot fail.", "HLAComVoice/vortigaunt/wecannotfail.wav")
AddVoice("WE EACH HAVE OUR PATHS", "We each have our paths.", "HLAComVoice/vortigaunt/weeachhaveourpaths.wav")
AddVoice("WE WILL NOT ALLOW IT", "We will not allow it.", "HLAComVoice/vortigaunt/wewillnotallow.wav")
AddVoice("YOUR JOURNEY", "Your journey brings you this far.", "HLAComVoice/vortigaunt/yourjourneybrings.wav")
AddVoice("V1", "Gerr...", "vortigaunt/ep2/vortigese02.wav")
AddVoice("V2", "Turr...", "vortigaunt/ep2/vortigese03.wav")
AddVoice("V3", "Lurr...", "vortigaunt/ep2/vortigese04.wav")
AddVoice("V4", "Lung...", "vortigaunt/ep2/vortigese05.wav")
AddVoice("V5", "Gung...", "vortigaunt/ep2/vortigese07.wav")
AddVoice("V6", "Gah'lung...", "vortigaunt/ep2/vortigese08.wav")
AddVoice("V7", "Galla'lung...", "vortigaunt/ep2/vortigese09.wav")
AddVoice("V8", "Turr, lung gurr challa'cher, gung, gong... lurr...", "vortigaunt/ep2/vortigese13.wav")

Schema.voices.AddClass("Biotic", function(ply)
    return ply:GetCharacter():GetFaction() == FACTION_VORT
end)